// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nexus.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SaveRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{1}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ReqData              []byte   `protobuf:"bytes,2,opt,name=reqData,proto3" json:"reqData,omitempty"`
	ResData              []byte   `protobuf:"bytes,3,opt,name=resData,proto3" json:"resData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{2}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SaveResponse) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *SaveResponse) GetResData() []byte {
	if m != nil {
		return m.ResData
	}
	return nil
}

type LoadRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{3}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoadResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ReqData              []byte   `protobuf:"bytes,2,opt,name=reqData,proto3" json:"reqData,omitempty"`
	ResData              []byte   `protobuf:"bytes,3,opt,name=resData,proto3" json:"resData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{4}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoadResponse) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *LoadResponse) GetResData() []byte {
	if m != nil {
		return m.ResData
	}
	return nil
}

type AddNodeRequest struct {
	NodeId               uint32   `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeUrl              string   `protobuf:"bytes,2,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{5}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *AddNodeRequest) GetNodeUrl() string {
	if m != nil {
		return m.NodeUrl
	}
	return ""
}

type RemoveNodeRequest struct {
	NodeId               uint32   `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRequest) Reset()         { *m = RemoveNodeRequest{} }
func (m *RemoveNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRequest) ProtoMessage()    {}
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{6}
}

func (m *RemoveNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRequest.Unmarshal(m, b)
}
func (m *RemoveNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRequest.Merge(m, src)
}
func (m *RemoveNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRequest.Size(m)
}
func (m *RemoveNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRequest proto.InternalMessageInfo

func (m *RemoveNodeRequest) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func init() {
	proto.RegisterType((*Status)(nil), "nexus.api.Status")
	proto.RegisterType((*SaveRequest)(nil), "nexus.api.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "nexus.api.SaveResponse")
	proto.RegisterType((*LoadRequest)(nil), "nexus.api.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "nexus.api.LoadResponse")
	proto.RegisterType((*AddNodeRequest)(nil), "nexus.api.AddNodeRequest")
	proto.RegisterType((*RemoveNodeRequest)(nil), "nexus.api.RemoveNodeRequest")
}

func init() { proto.RegisterFile("nexus.proto", fileDescriptor_6bc6d570457f57a9) }

var fileDescriptor_6bc6d570457f57a9 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x6d, 0x93, 0xd2, 0x49, 0x15, 0xba, 0x87, 0x1a, 0x8b, 0x87, 0x9a, 0x53, 0x45, 0xc8,
	0xa1, 0x82, 0x39, 0x79, 0xb0, 0x78, 0x11, 0xa4, 0x87, 0x2d, 0x5e, 0xbc, 0xad, 0xee, 0x20, 0x05,
	0x93, 0x4d, 0xb3, 0x49, 0xf1, 0xb7, 0xfd, 0x03, 0xd9, 0xc9, 0xa6, 0x4d, 0x88, 0xa0, 0x27, 0x6f,
	0xf3, 0x32, 0x6f, 0x66, 0xde, 0x7b, 0x59, 0xf0, 0x53, 0xfc, 0x2c, 0x75, 0x94, 0xe5, 0xaa, 0x50,
	0x6c, 0x54, 0x01, 0x91, 0x6d, 0xc3, 0x5b, 0xf0, 0x36, 0x85, 0x28, 0x4a, 0xcd, 0x18, 0x0c, 0xde,
	0x94, 0xc4, 0xc0, 0x99, 0x3b, 0x0b, 0x97, 0x53, 0xcd, 0x02, 0x18, 0x26, 0xa8, 0xb5, 0x78, 0xc7,
	0xa0, 0x37, 0x77, 0x16, 0x23, 0x5e, 0xc3, 0xf0, 0x12, 0xfc, 0x8d, 0xd8, 0x23, 0xc7, 0x5d, 0x89,
	0xba, 0x30, 0xc3, 0x52, 0x14, 0x82, 0x86, 0xc7, 0x9c, 0xea, 0x30, 0x81, 0x71, 0x45, 0xd1, 0x99,
	0x4a, 0x35, 0xb2, 0x2b, 0xf0, 0x34, 0x9d, 0x22, 0x96, 0xbf, 0x9c, 0x44, 0x07, 0x19, 0x51, 0xa5,
	0x81, 0x5b, 0x82, 0xb9, 0x9b, 0xe3, 0xee, 0xc1, 0x6c, 0xec, 0xd1, 0xc6, 0x1a, 0x56, 0x1d, 0x4d,
	0x9d, 0x7e, 0xdd, 0x21, 0x68, 0x14, 0x3d, 0x29, 0x21, 0x7f, 0x51, 0x54, 0x51, 0xfe, 0x47, 0xd1,
	0x0a, 0x4e, 0xef, 0xa5, 0x5c, 0x2b, 0x79, 0x88, 0x69, 0x0a, 0x5e, 0xaa, 0x24, 0x3e, 0x4a, 0x3a,
	0x78, 0xc2, 0x2d, 0x32, 0x3b, 0x4c, 0xf5, 0x9c, 0x7f, 0xd4, 0x39, 0x5b, 0x18, 0x5e, 0xc3, 0x84,
	0x63, 0xa2, 0xf6, 0xf8, 0x87, 0x35, 0xcb, 0x2f, 0x07, 0xdc, 0xb5, 0x71, 0xc0, 0x62, 0x18, 0x98,
	0xec, 0xd9, 0xb4, 0xe9, 0xe8, 0xf8, 0xbf, 0x66, 0x67, 0x9d, 0xef, 0x36, 0x92, 0x18, 0x06, 0x26,
	0xa2, 0xd6, 0x60, 0x23, 0xd6, 0xd6, 0x60, 0x2b, 0xcb, 0x18, 0x86, 0xd6, 0x2c, 0x3b, 0x6f, 0x70,
	0xda, 0x01, 0xcc, 0xba, 0x09, 0xb3, 0x3b, 0x80, 0xa3, 0x43, 0x76, 0xd1, 0x20, 0x74, 0x8c, 0xff,
	0x30, 0xbe, 0x72, 0x5f, 0xfa, 0x22, 0xdb, 0xbe, 0x7a, 0xf4, 0xb2, 0x6f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xdf, 0xfd, 0x97, 0xfc, 0xe8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NexusClient is the client API for Nexus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NexusClient interface {
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error)
}

type nexusClient struct {
	cc *grpc.ClientConn
}

func NewNexusClient(cc *grpc.ClientConn) NexusClient {
	return &nexusClient{cc}
}

func (c *nexusClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusServer is the server API for Nexus service.
type NexusServer interface {
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	AddNode(context.Context, *AddNodeRequest) (*Status, error)
	RemoveNode(context.Context, *RemoveNodeRequest) (*Status, error)
}

// UnimplementedNexusServer can be embedded to have forward compatible implementations.
type UnimplementedNexusServer struct {
}

func (*UnimplementedNexusServer) Save(ctx context.Context, req *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedNexusServer) Load(ctx context.Context, req *LoadRequest) (*LoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedNexusServer) AddNode(ctx context.Context, req *AddNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (*UnimplementedNexusServer) RemoveNode(ctx context.Context, req *RemoveNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}

func RegisterNexusServer(s *grpc.Server, srv NexusServer) {
	s.RegisterService(&_Nexus_serviceDesc, srv)
}

func _Nexus_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nexus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.api.Nexus",
	HandlerType: (*NexusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _Nexus_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Nexus_Load_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _Nexus_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _Nexus_RemoveNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}
