// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nexus.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	nexus.proto

It has these top-level messages:
	InsertKVRequest
	DeleteKVRequest
	Relation
	InsertRelRequest
	DeleteRelRequest
	StatusResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InsertKVRequest struct {
	Key     []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Options map[string][]byte `protobuf:"bytes,3,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *InsertKVRequest) Reset()                    { *m = InsertKVRequest{} }
func (m *InsertKVRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertKVRequest) ProtoMessage()               {}
func (*InsertKVRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InsertKVRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *InsertKVRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *InsertKVRequest) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type DeleteKVRequest struct {
	Key     []byte            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Options map[string][]byte `protobuf:"bytes,3,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *DeleteKVRequest) Reset()                    { *m = DeleteKVRequest{} }
func (m *DeleteKVRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteKVRequest) ProtoMessage()               {}
func (*DeleteKVRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteKVRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DeleteKVRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DeleteKVRequest) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type Relation struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Relation) Reset()                    { *m = Relation{} }
func (m *Relation) String() string            { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()               {}
func (*Relation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Relation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Relation) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InsertRelRequest struct {
	Relations []*Relation       `protobuf:"bytes,1,rep,name=relations" json:"relations,omitempty"`
	Options   map[string][]byte `protobuf:"bytes,2,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *InsertRelRequest) Reset()                    { *m = InsertRelRequest{} }
func (m *InsertRelRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertRelRequest) ProtoMessage()               {}
func (*InsertRelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InsertRelRequest) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *InsertRelRequest) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type DeleteRelRequest struct {
	Relations []*Relation       `protobuf:"bytes,1,rep,name=relations" json:"relations,omitempty"`
	Options   map[string][]byte `protobuf:"bytes,2,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *DeleteRelRequest) Reset()                    { *m = DeleteRelRequest{} }
func (m *DeleteRelRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRelRequest) ProtoMessage()               {}
func (*DeleteRelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRelRequest) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *DeleteRelRequest) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type StatusResponse struct {
	Code    int32             `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Options map[string][]byte `protobuf:"bytes,3,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StatusResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatusResponse) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*InsertKVRequest)(nil), "nexus.api.InsertKVRequest")
	proto.RegisterType((*DeleteKVRequest)(nil), "nexus.api.DeleteKVRequest")
	proto.RegisterType((*Relation)(nil), "nexus.api.Relation")
	proto.RegisterType((*InsertRelRequest)(nil), "nexus.api.InsertRelRequest")
	proto.RegisterType((*DeleteRelRequest)(nil), "nexus.api.DeleteRelRequest")
	proto.RegisterType((*StatusResponse)(nil), "nexus.api.StatusResponse")
}

func init() { proto.RegisterFile("nexus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x84, 0x50, 0x72, 0xad, 0xa0, 0x32, 0x0c, 0x11, 0x53, 0xd5, 0x01, 0x32, 0x45,
	0xa2, 0x2c, 0xa8, 0x13, 0x54, 0x30, 0x20, 0x06, 0x24, 0x23, 0x31, 0xb0, 0x19, 0x7a, 0x42, 0x11,
	0xa9, 0x6d, 0x62, 0x07, 0xd1, 0x7f, 0xc6, 0xc0, 0xca, 0xff, 0x42, 0xb1, 0x13, 0x12, 0x82, 0xc4,
	0xd4, 0x6c, 0x77, 0xae, 0xdf, 0x7b, 0xf7, 0xf9, 0xaa, 0xc0, 0x50, 0xe0, 0x7b, 0xa1, 0x13, 0x95,
	0x4b, 0x23, 0x69, 0xe8, 0x1a, 0xae, 0xd2, 0xe9, 0x07, 0x81, 0xbd, 0x6b, 0xa1, 0x31, 0x37, 0x37,
	0xf7, 0x0c, 0x5f, 0x0b, 0xd4, 0x86, 0x8e, 0xc1, 0x7f, 0xc1, 0x75, 0x44, 0x26, 0x24, 0x1e, 0xb1,
	0xb2, 0xa4, 0x07, 0x10, 0xbc, 0xf1, 0xac, 0xc0, 0xc8, 0xb3, 0x67, 0xae, 0xa1, 0x17, 0x30, 0x90,
	0xca, 0xa4, 0x52, 0xe8, 0xc8, 0x9f, 0xf8, 0xf1, 0x70, 0x76, 0x9c, 0xfc, 0x18, 0x27, 0x1d, 0xd3,
	0xe4, 0xd6, 0xdd, 0xbc, 0x12, 0x26, 0x5f, 0xb3, 0x5a, 0x77, 0x38, 0x87, 0x51, 0xfb, 0x87, 0x76,
	0x74, 0xf8, 0x4f, 0xf4, 0xdc, 0x3b, 0x23, 0x76, 0xf4, 0x4b, 0xcc, 0xd0, 0xe0, 0x86, 0x47, 0xef,
	0x98, 0xf6, 0x30, 0xfa, 0x0c, 0x76, 0x18, 0x66, 0xbc, 0x54, 0x53, 0x0a, 0x5b, 0x82, 0xaf, 0xb0,
	0x12, 0xda, 0xba, 0x3c, 0x5b, 0x72, 0xc3, 0x2b, 0xa1, 0xad, 0xa7, 0x5f, 0x04, 0xc6, 0xee, 0x51,
	0x19, 0x66, 0x35, 0xef, 0x09, 0x84, 0x79, 0x65, 0xa4, 0x23, 0x62, 0x49, 0xf6, 0x5b, 0x24, 0x75,
	0x08, 0x6b, 0x6e, 0xd1, 0x45, 0x83, 0xee, 0x59, 0x41, 0xfc, 0x67, 0x6b, 0x4d, 0x40, 0x0f, 0xec,
	0x25, 0x87, 0x7b, 0xe1, 0x1e, 0x39, 0xba, 0x01, 0x3d, 0x70, 0x7c, 0x12, 0xd8, 0xbd, 0x33, 0xdc,
	0x14, 0x9a, 0xa1, 0x56, 0x52, 0x68, 0xbb, 0xb6, 0x27, 0xb9, 0x74, 0xab, 0x0c, 0x98, 0xad, 0x69,
	0x04, 0x83, 0x15, 0x6a, 0xcd, 0x9f, 0x9d, 0x45, 0xc8, 0xea, 0x96, 0x9e, 0x77, 0xff, 0x83, 0x47,
	0x2d, 0x80, 0xdf, 0xce, 0x9b, 0x1f, 0x7f, 0x11, 0x3c, 0xf8, 0x5c, 0xa5, 0x8f, 0xdb, 0xf6, 0x8b,
	0x70, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x7d, 0xe4, 0xe8, 0x20, 0x04, 0x00, 0x00,
}
