// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nexus.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{9, 0}
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SaveRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{1}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ReqData              []byte   `protobuf:"bytes,2,opt,name=reqData,proto3" json:"reqData,omitempty"`
	ResData              []byte   `protobuf:"bytes,3,opt,name=resData,proto3" json:"resData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{2}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SaveResponse) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *SaveResponse) GetResData() []byte {
	if m != nil {
		return m.ResData
	}
	return nil
}

type LoadRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{3}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoadResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ReqData              []byte   `protobuf:"bytes,2,opt,name=reqData,proto3" json:"reqData,omitempty"`
	ResData              []byte   `protobuf:"bytes,3,opt,name=resData,proto3" json:"resData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{4}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoadResponse) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *LoadResponse) GetResData() []byte {
	if m != nil {
		return m.ResData
	}
	return nil
}

type AddNodeRequest struct {
	NodeUrl              string   `protobuf:"bytes,1,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{5}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetNodeUrl() string {
	if m != nil {
		return m.NodeUrl
	}
	return ""
}

type RemoveNodeRequest struct {
	NodeUrl              string   `protobuf:"bytes,1,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRequest) Reset()         { *m = RemoveNodeRequest{} }
func (m *RemoveNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRequest) ProtoMessage()    {}
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{6}
}

func (m *RemoveNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRequest.Unmarshal(m, b)
}
func (m *RemoveNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRequest.Merge(m, src)
}
func (m *RemoveNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRequest.Size(m)
}
func (m *RemoveNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRequest proto.InternalMessageInfo

func (m *RemoveNodeRequest) GetNodeUrl() string {
	if m != nil {
		return m.NodeUrl
	}
	return ""
}

type ListNodesResponse struct {
	Status               *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Leader               uint64            `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Nodes                map[uint64]string `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{7}
}

func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (m *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(m, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListNodesResponse) GetLeader() uint64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *ListNodesResponse) GetNodes() map[uint64]string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{8}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=nexus.api.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bc6d570457f57a9, []int{9}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("nexus.api.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Status)(nil), "nexus.api.Status")
	proto.RegisterType((*SaveRequest)(nil), "nexus.api.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "nexus.api.SaveResponse")
	proto.RegisterType((*LoadRequest)(nil), "nexus.api.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "nexus.api.LoadResponse")
	proto.RegisterType((*AddNodeRequest)(nil), "nexus.api.AddNodeRequest")
	proto.RegisterType((*RemoveNodeRequest)(nil), "nexus.api.RemoveNodeRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "nexus.api.ListNodesResponse")
	proto.RegisterMapType((map[uint64]string)(nil), "nexus.api.ListNodesResponse.NodesEntry")
	proto.RegisterType((*HealthCheckRequest)(nil), "nexus.api.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "nexus.api.HealthCheckResponse")
}

func init() { proto.RegisterFile("nexus.proto", fileDescriptor_6bc6d570457f57a9) }

var fileDescriptor_6bc6d570457f57a9 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0xd3, 0xaa, 0x37, 0x63, 0xb4, 0x06, 0x95, 0x10, 0x06, 0x2a, 0x79, 0xa1, 0x20,
	0xc8, 0xa4, 0x22, 0xb1, 0x69, 0xd2, 0x1e, 0x06, 0x2b, 0x1f, 0x62, 0xca, 0x24, 0x97, 0x81, 0xc4,
	0x0b, 0xf2, 0x9a, 0x4b, 0x57, 0x2d, 0x8d, 0xb3, 0x38, 0xa9, 0xe8, 0x2f, 0xe1, 0x67, 0xf1, 0x87,
	0x78, 0x40, 0x76, 0x92, 0x36, 0x51, 0xc7, 0x40, 0x3c, 0xec, 0x2d, 0xc7, 0xf7, 0x1c, 0xdf, 0xe3,
	0x9b, 0x63, 0x83, 0x19, 0xe2, 0xf7, 0x54, 0xb8, 0x51, 0xcc, 0x13, 0x4e, 0x5a, 0x19, 0x60, 0xd1,
	0xd4, 0xbe, 0x3f, 0xe1, 0x7c, 0x12, 0xe0, 0xb6, 0x2a, 0x9c, 0xa6, 0xdf, 0xb6, 0x71, 0x16, 0x25,
	0x8b, 0x8c, 0xe7, 0xbc, 0x84, 0xc6, 0x28, 0x61, 0x49, 0x2a, 0x08, 0x81, 0xfa, 0x98, 0xfb, 0x68,
	0x69, 0x3d, 0xad, 0x6f, 0x50, 0xf5, 0x4d, 0x2c, 0x68, 0xce, 0x50, 0x08, 0x36, 0x41, 0xab, 0xd6,
	0xd3, 0xfa, 0x2d, 0x5a, 0x40, 0xe7, 0x11, 0x98, 0x23, 0x36, 0x47, 0x8a, 0x17, 0x29, 0x8a, 0x44,
	0x8a, 0x7d, 0x96, 0x30, 0x25, 0xde, 0xa0, 0xea, 0xdb, 0x99, 0xc1, 0x46, 0x46, 0x11, 0x11, 0x0f,
	0x05, 0x92, 0x27, 0xd0, 0x10, 0xaa, 0x95, 0x62, 0x99, 0x83, 0x8e, 0xbb, 0xf4, 0xe8, 0x66, 0x1e,
	0x68, 0x4e, 0x90, 0x7d, 0x63, 0xbc, 0x38, 0x94, 0x3b, 0xd6, 0xd4, 0x8e, 0x05, 0xcc, 0x2a, 0x42,
	0x55, 0xf4, 0xa2, 0xa2, 0xa0, 0x74, 0x74, 0xc4, 0x99, 0xff, 0x17, 0x47, 0x19, 0xe5, 0x7a, 0x1c,
	0x3d, 0x85, 0xcd, 0x03, 0xdf, 0xf7, 0xb8, 0xbf, 0x1c, 0x93, 0x05, 0xcd, 0x90, 0xfb, 0x78, 0x12,
	0x07, 0xaa, 0x63, 0x8b, 0x16, 0xd0, 0x79, 0x0e, 0x1d, 0x8a, 0x33, 0x3e, 0xc7, 0x7f, 0xa3, 0xff,
	0xd4, 0xa0, 0x73, 0x34, 0x15, 0x89, 0x64, 0x8b, 0xff, 0x39, 0x4f, 0x17, 0x1a, 0x01, 0x32, 0x1f,
	0x63, 0x75, 0x9c, 0x3a, 0xcd, 0x11, 0xd9, 0x07, 0x43, 0xf6, 0x10, 0x96, 0xde, 0xd3, 0xfb, 0xe6,
	0xe0, 0x71, 0x69, 0x87, 0xb5, 0x7e, 0xae, 0x42, 0xc3, 0x30, 0x89, 0x17, 0x34, 0x53, 0xd9, 0xbb,
	0x00, 0xab, 0x45, 0xd2, 0x06, 0xfd, 0x1c, 0x17, 0xca, 0x4c, 0x9d, 0xca, 0x4f, 0x72, 0x07, 0x8c,
	0x39, 0x0b, 0xd2, 0x22, 0x4e, 0x19, 0xd8, 0xab, 0xed, 0x6a, 0x8e, 0x0b, 0xe4, 0x1d, 0xb2, 0x20,
	0x39, 0x7b, 0x7d, 0x86, 0xe3, 0xf3, 0xd2, 0x04, 0x04, 0xc6, 0xf3, 0xe9, 0x18, 0x8b, 0x09, 0xe4,
	0xd0, 0xf9, 0xa1, 0xc1, 0xed, 0x8a, 0x20, 0x9f, 0xc1, 0x61, 0x65, 0x06, 0x9b, 0x83, 0x67, 0xa5,
	0x13, 0x5c, 0xc2, 0x77, 0x47, 0x72, 0xbf, 0x70, 0x52, 0x1d, 0x8f, 0xb3, 0x07, 0x37, 0x2b, 0x05,
	0x62, 0x42, 0xf3, 0xc4, 0xfb, 0xe0, 0x1d, 0x7f, 0xf6, 0xda, 0x37, 0x24, 0x18, 0x0d, 0xe9, 0xa7,
	0xf7, 0xde, 0xdb, 0xb6, 0x46, 0x6e, 0x81, 0xe9, 0x1d, 0x7f, 0xfc, 0x5a, 0x2c, 0xd4, 0x06, 0xbf,
	0x6a, 0x60, 0x78, 0xb2, 0x27, 0x79, 0x03, 0x86, 0x6a, 0x46, 0x1e, 0xfc, 0xc9, 0x84, 0x3a, 0xa5,
	0xfd, 0xf0, 0x6a, 0x8f, 0x64, 0x07, 0xea, 0xf2, 0x26, 0x91, 0x6e, 0xf9, 0x7f, 0xae, 0x6e, 0x9f,
	0x7d, 0x77, 0x6d, 0x7d, 0x25, 0x94, 0x81, 0xaf, 0x08, 0x4b, 0x97, 0xa4, 0x22, 0xac, 0xdc, 0x8c,
	0x1d, 0x68, 0xe6, 0xd1, 0x25, 0xf7, 0x4a, 0x9c, 0x6a, 0x9c, 0xed, 0xf5, 0x7c, 0x91, 0x7d, 0x80,
	0x55, 0x8e, 0xc9, 0x56, 0x89, 0xb0, 0x16, 0xef, 0xcb, 0xe4, 0x07, 0xd0, 0x5a, 0xc6, 0x8c, 0x74,
	0xdd, 0xec, 0xe5, 0x72, 0x8b, 0x97, 0xcb, 0x1d, 0xca, 0x97, 0xcb, 0xde, 0xba, 0x2a, 0x94, 0xaf,
	0x8c, 0x2f, 0x3a, 0x8b, 0xa6, 0xa7, 0x0d, 0x25, 0x7a, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x66,
	0x23, 0x35, 0xfb, 0x16, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NexusClient is the client API for Nexus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NexusClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error)
	ListNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type nexusClient struct {
	cc *grpc.ClientConn
}

func NewNexusClient(cc *grpc.ClientConn) NexusClient {
	return &nexusClient{cc}
}

func (c *nexusClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusClient) ListNodes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, "/nexus.api.Nexus/ListNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusServer is the server API for Nexus service.
type NexusServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	AddNode(context.Context, *AddNodeRequest) (*Status, error)
	RemoveNode(context.Context, *RemoveNodeRequest) (*Status, error)
	ListNodes(context.Context, *empty.Empty) (*ListNodesResponse, error)
}

// UnimplementedNexusServer can be embedded to have forward compatible implementations.
type UnimplementedNexusServer struct {
}

func (*UnimplementedNexusServer) Check(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedNexusServer) Save(ctx context.Context, req *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedNexusServer) Load(ctx context.Context, req *LoadRequest) (*LoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedNexusServer) AddNode(ctx context.Context, req *AddNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (*UnimplementedNexusServer) RemoveNode(ctx context.Context, req *RemoveNodeRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}
func (*UnimplementedNexusServer) ListNodes(ctx context.Context, req *empty.Empty) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}

func RegisterNexusServer(s *grpc.Server, srv NexusServer) {
	s.RegisterService(&_Nexus_serviceDesc, srv)
}

func _Nexus_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nexus_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.api.Nexus/ListNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusServer).ListNodes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nexus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.api.Nexus",
	HandlerType: (*NexusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Nexus_Check_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Nexus_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Nexus_Load_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _Nexus_AddNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _Nexus_RemoveNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Nexus_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}
