name: Nexus CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build & Test Nexus
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
       redis-version: 5

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
