// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: models/internal.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo_NodeStatus int32

const (
	NodeInfo_LEADER    NodeInfo_NodeStatus = 0
	NodeInfo_CANDIDATE NodeInfo_NodeStatus = 1
	NodeInfo_FOLLOWER  NodeInfo_NodeStatus = 2
	NodeInfo_OFFLINE   NodeInfo_NodeStatus = 3
	NodeInfo_UNKNOWN   NodeInfo_NodeStatus = 4
)

// Enum value maps for NodeInfo_NodeStatus.
var (
	NodeInfo_NodeStatus_name = map[int32]string{
		0: "LEADER",
		1: "CANDIDATE",
		2: "FOLLOWER",
		3: "OFFLINE",
		4: "UNKNOWN",
	}
	NodeInfo_NodeStatus_value = map[string]int32{
		"LEADER":    0,
		"CANDIDATE": 1,
		"FOLLOWER":  2,
		"OFFLINE":   3,
		"UNKNOWN":   4,
	}
)

func (x NodeInfo_NodeStatus) Enum() *NodeInfo_NodeStatus {
	p := new(NodeInfo_NodeStatus)
	*p = x
	return p
}

func (x NodeInfo_NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeInfo_NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_internal_proto_enumTypes[0].Descriptor()
}

func (NodeInfo_NodeStatus) Type() protoreflect.EnumType {
	return &file_models_internal_proto_enumTypes[0]
}

func (x NodeInfo_NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeInfo_NodeStatus.Descriptor instead.
func (NodeInfo_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_internal_proto_rawDescGZIP(), []int{1, 0}
}

type NexusInternalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID  uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Req []byte `protobuf:"bytes,2,opt,name=Req,proto3" json:"Req,omitempty"`
}

func (x *NexusInternalRequest) Reset() {
	*x = NexusInternalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NexusInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusInternalRequest) ProtoMessage() {}

func (x *NexusInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusInternalRequest.ProtoReflect.Descriptor instead.
func (*NexusInternalRequest) Descriptor() ([]byte, []int) {
	return file_models_internal_proto_rawDescGZIP(), []int{0}
}

func (x *NexusInternalRequest) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NexusInternalRequest) GetReq() []byte {
	if x != nil {
		return x.Req
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeUrl string              `protobuf:"bytes,1,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
	NodeId  uint64              `protobuf:"varint,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Status  NodeInfo_NodeStatus `protobuf:"varint,3,opt,name=status,proto3,enum=models.NodeInfo_NodeStatus" json:"status,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_models_internal_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeUrl() string {
	if x != nil {
		return x.NodeUrl
	}
	return ""
}

func (x *NodeInfo) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetStatus() NodeInfo_NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeInfo_LEADER
}

var File_models_internal_proto protoreflect.FileDescriptor

var file_models_internal_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22,
	0x38, 0x0a, 0x14, 0x4e, 0x65, 0x78, 0x75, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x65, 0x71, 0x22, 0xc2, 0x01, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x4c,
	0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x44, 0x49,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57,
	0x45, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x69,
	0x70, 0x6b, 0x61, 0x72, 0x74, 0x2d, 0x69, 0x6e, 0x63, 0x75, 0x62, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x6e, 0x65, 0x78, 0x75, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_internal_proto_rawDescOnce sync.Once
	file_models_internal_proto_rawDescData = file_models_internal_proto_rawDesc
)

func file_models_internal_proto_rawDescGZIP() []byte {
	file_models_internal_proto_rawDescOnce.Do(func() {
		file_models_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_internal_proto_rawDescData)
	})
	return file_models_internal_proto_rawDescData
}

var file_models_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_internal_proto_goTypes = []interface{}{
	(NodeInfo_NodeStatus)(0),     // 0: models.NodeInfo.NodeStatus
	(*NexusInternalRequest)(nil), // 1: models.NexusInternalRequest
	(*NodeInfo)(nil),             // 2: models.NodeInfo
}
var file_models_internal_proto_depIdxs = []int32{
	0, // 0: models.NodeInfo.status:type_name -> models.NodeInfo.NodeStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_internal_proto_init() }
func file_models_internal_proto_init() {
	if File_models_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NexusInternalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_internal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_internal_proto_goTypes,
		DependencyIndexes: file_models_internal_proto_depIdxs,
		EnumInfos:         file_models_internal_proto_enumTypes,
		MessageInfos:      file_models_internal_proto_msgTypes,
	}.Build()
	File_models_internal_proto = out.File
	file_models_internal_proto_rawDesc = nil
	file_models_internal_proto_goTypes = nil
	file_models_internal_proto_depIdxs = nil
}
